apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpneQpNVE01TURKYUZ3MDBNekF4TWpneU1UTTVNREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDOFowSXZtK2p5RExEbnowWEtpalNCQnNIZWhHaGJpRTdIOEJlR01ZQWVoTlBSUmdyZwpzVUNWT2VYbFpoYnJaOXU1ZHE0ZlZ5QlVrTFFiM1RrMUladGs0Y3dGQXRpaDJob3hRMVR4RGZ4c1huTnpySEJSCmdERndEdFBPL2RGYWU5KzE0SjVYNzhQMU5QOWlKS0src2NnTUJyT1lJTXhZTXk1N0o4R3NwdE42UmFwaDk5M0UKSERManZqcnNGYkU4UTBRWFJWZXhUbUdyandvUzBLZ2xCTnErYUZrRGZDVU1HUUtYZHRtb0w4WEE2NmhkQVY1VApTZFQzZWREOE8rRzRBN0U5OEs4L1ZIQVppR0p5MFJZUlJBSGQ5SDdBYjcraTJ1RXdCVCswajVKM3M5OXlDdHd4Ck00UzZGNzlGaklFWXh3Qmt1TDZQUENqUjB1NDgwYzFIYWQ4YkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRodzdkVVpqb0M5SjBZdDBlMgowaWRwSzdVYWpUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFCMDFxWkRHSXlvQjRON2o2VnVDWWMyZUtPaEV1CkUrdWV1NjNPTVMrUGdDVlFKc3ZWMXVMK01KL25HVzlGbm0zUDJJL09GTVBLYndYMXhqRjhDakN6UTRWT3JyYlQKeDBWeWJTbUw4dDUvV3RONGU4RS9FY2JwSHB0TCsrV2xoT21WTk9KcTRNc3JETDZpeEsxL0NmL1pjTkJWdXhBRQpKdk9FakhueWo3bjZWQjlKNXd6bDZUN0FQMTkzZDJlcWIvVndsMUx5Vm8zTUFGcVR6bWdBWWZlZ2I2Q0ZHUjMvCk9nUjNFdzRwcmpubWlDYm96a0NUSzg5b0ZoWDlaRXE5M3MzeFFkUXhaYWNZakJvRWpNQm9OUDlMM0FzbE5idFkKRXpEYkYxdGU0TTRKVHluVTZLaStGK1ZuWXBNSmx0bFIrZjU1OWRCSGJraG1TNDJlWXJhUDVHT2d6dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c4702c10-a392-4230-b1d2-7ab9e2ad5a99.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_4a421c4f630f878a0193b7d69d5039617d7f96cb1f93da191e09e7c542fe8683
